[package]
name = "seed-split"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subtle="2.4.1"

[dev-dependencies]
proptest = "1.0.0"
